version: '3.8'
services:
  web:
    build: .
    container_name: dog-inventory-web
    environment:
      - PORT=3000
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=dogsdb
      - DB_HOST=db
      - DB_PORT=5432
      - JWT_SECRET=your_jwt_secret
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    container_name: dog-inventory-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dogsdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
